

spring:
  application:
    name: example2-service


  datasource:
    url: jdbc:mysql://localhost:3306/msa2?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: msa
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9998


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
  jackson:
    enabled: true

logging:
  level:
    com.example.simple.client: DEBUG
    feign: DEBUG