server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: example-service
          uri: lb://example-service
          predicates:
            - Path=/api/example/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: example2-service
          uri: lb://example2-service
          predicates:
            - Path=/api/example2/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: gathering-service
          uri: lb://gathering-service
          predicates:
            - Path=/api/gathering/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/board/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

        - id: information-service
          uri: lb://information-service
          predicates:
            - Path=/api/information/**
          filters:
            - StripPrefix=2
            - SetRequestHeader=Accept, application/json

        - id: qna-service
          uri: lb://qna-service
          predicates:
            - Path=/api/qna/**
          filters:
            - StripPrefix=2
            - SetRequestHeader=Accept, application/json

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka